require('dotenv').config(); // Load environment variables

const express = require('express');
const router = express.Router();
const User = require('../models/User');
const nodemailer = require('nodemailer');
const PDFDocument = require('pdfkit');
const path = require('path');
const fs = require('fs');

// Ensure 'pdfs' folder exists
const pdfDir = path.join(__dirname, '../pdfs');
if (!fs.existsSync(pdfDir)) {
  fs.mkdirSync(pdfDir, { recursive: true });
}

// Registration Route
router.post('/register', async (req, res) => {
  try {
    const { name, email, phone, tshirtSize, feeStatus } = req.body;

    // Check if email or phone already exists
    const existingUserByEmail = await User.findOne({ email });
    const existingUserByPhone = await User.findOne({ phone });

    if (existingUserByEmail) {
      return res.status(400).json({ success: false, message: '❌ Email is already in use. Please use a different email.' });
    }

    if (existingUserByPhone) {
      return res.status(400).json({ success: false, message: '❌ Phone number is already in use. Please use a different phone number.' });
    }

    // Save user in database
    const newUser = new User({ name, email, phone, tshirtSize, feeStatus });
    await newUser.save();
// Generate PDF
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const pdfPath = path.join(pdfDir, `registration-${newUser._id}.pdf`);
    doc.pipe(fs.createWriteStream(pdfPath));

    // Add logo with adjusted margin below it
    const logoPath = path.join(__dirname, '../assets/logo.png'); // Make sure to put your logo here
    doc.image(logoPath, 50, 30, { width: 100 }).moveDown(2); // Increased margin (moveDown(2)) below the logo

    // Title with adjusted margin below it
    doc.fontSize(22).font('Helvetica-Bold').text(`Registration Details`, { align: 'center' }).moveDown(1.5); // Increased margin below title

    // Draw a box around the user details section
    const boxX = 50; // X position of the box
    const boxY = doc.y + 10; // Y position, to avoid overlap with title
    const boxWidth = 500; // Width of the box
    const boxHeight = 140; // Height of the box

    // Draw the box (rectangle)
    doc.rect(boxX, boxY, boxWidth, boxHeight).stroke();

    // Add content inside the box
    const contentX = boxX + 10; // X position inside the box (10 units from left edge)
    const contentY = boxY + 10; // Y position inside the box (10 units from top edge)

    // Set font for content inside the box
    doc.fontSize(12).font('Helvetica');

    // Add the user details inside the box
    doc.text(`Name: ${name}`, contentX, contentY);
    doc.text(`Email: ${email}`, contentX, contentY + 20);
    doc.text(`Phone: ${phone}`, contentX, contentY + 40);
    doc.text(`T-Shirt Size: ${tshirtSize}`, contentX, contentY + 60);
    doc.text(`Fee Status: ${feeStatus}`, contentX, contentY + 80);

    // Leave space between the box and footer
    doc.moveDown(7); // Adds space between the box and the footer

    // Add footer with contact information
    doc.fontSize(10).text('Thank you for registering with Special Economic Care Coaching Centre.', { align: 'center' });
    doc.fontSize(10).text('THIS DOCUMENT IS GENERATED BY @||ZUBAYER HOSSEN||', { align: 'center' });
    doc.fontSize(20).text('FOR ANY QUERY: ', { align: 'center' });
    doc.fontSize(10).text('SHAHADAT HOSSAIN: 01906-354505  ||  CALL to: ABDULLAH AL MAMUN: 01925-551630 ', { align: 'center' });
    
    doc.moveDown(10); // Adds space after footer
    doc.fontSize(20).text(`"Unveil the Wonders, Embrace the Adventure – Your Dream Journey Begins Here!" `, { align: 'center' });
    doc.end();

    // Setup Email Transporter
    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.EMAIL,
        pass: process.env.EMAIL_PASS,
      },
    });

    // Send Email to Admin
    const adminMailOptions = {
      from: process.env.EMAIL,
      to: process.env.ADMIN_EMAIL,
      bcc: process.env.ADMIN_EMAIL2,
      subject: '🎉 New Registration Alert - Special Economics Care Coaching Centre',
       html: `
    <div style="max-width: 600px; margin: auto; font-family: Arial, sans-serif; border-radius: 10px; padding: 20px; background-color: #ffffff; box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);">
      
      <!-- Header -->
      <div style="background: linear-gradient(135deg, #007bff, #0056b3); color: white; text-align: center; padding: 20px; border-top-left-radius: 10px; border-top-right-radius: 10px;">
        <h2 style="margin: 0; font-size: 22px;">🎟 Special Economics Care Coaching Centre</h2>
        <p style="margin: 5px 0; font-size: 16px;">New Registration Notification</p>
      </div>

      <!-- Body -->
      <div style="padding: 20px;">
        <p><strong>Dear Admin,</strong></p>
        <p>A new user has registered for the tour. Here are the details:</p>
        
        <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
          <tr>
            <td style="padding: 10px; border: 1px solid #ddd; background-color: #f8f9fa;"><strong>👤 Name:</strong></td>
            <td style="padding: 10px; border: 1px solid #ddd;">${name}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #ddd; background-color: #f8f9fa;"><strong>📧 Email:</strong></td>
            <td style="padding: 10px; border: 1px solid #ddd;">${email}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #ddd; background-color: #f8f9fa;"><strong>📞 Phone:</strong></td>
            <td style="padding: 10px; border: 1px solid #ddd;">${phone}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #ddd; background-color: #f8f9fa;"><strong>👕 T-Shirt Size:</strong></td>
            <td style="padding: 10px; border: 1px solid #ddd;">${tshirtSize}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #ddd; background-color: #f8f9fa;"><strong>💰 Fee Status:</strong></td>
            <td style="padding: 10px; border: 1px solid #ddd; color: ${feeStatus === 'Paid' ? 'green' : 'red'};"><strong>${feeStatus}</strong></td>
          </tr>
        </table>

        <!-- Ticket Download Button -->
        <p style="margin-top: 20px; text-align: center;">
          <a href="https://tour-user.onrender.com/pdfs/registration-${newUser._id}.pdf"
             style="background-color: #007bff; color: white; padding: 12px 20px; text-decoration: none; font-weight: bold; border-radius: 5px; display: inline-block; transition: background 0.3s;">
            📥 Download Registration Ticket
          </a>
        </p>

        <!-- Gallery Section -->
        <h3 style="text-align: center; color: #0056b3; margin-top: 30px;">🌍 Adventure Awaits! Explore Our Tour Destinations!</h3>
        <div style="display: flex; flex-wrap: wrap; justify-content: center; gap: 10px;">
          <img src="https://skhobor.com/image/news/Jessore%20Airport%2029032022-1.jpg" style="width: 30%; border-radius: 10px;">
          <img src="https://i.ibb.co/5x5SmwQK/67744235-495910207826030-6821001493089353728-n.jpg" style="width: 30%; border-radius: 10px;">
          <img src="https://www.mawbiz.com.bd/application/views/module/logo_image/logo52.jpg" style="width: 30%; border-radius: 10px;">
        </div>
      </div>

   <!-- Signature Section -->
<div style="border-top: 2px solid #007bff; padding: 25px; margin-top: 30px; text-align: center; background: linear-gradient(135deg, #f8f9fa, #ffffff); box-shadow: 0px 5px 15px rgba(0, 0, 0, 0.15); border-radius: 10px;">
  
  <!-- Profile Image -->
  <div style="display: flex; justify-content: center; align-items: center; margin-bottom: 10px;">
    <img src="https://pbs.twimg.com/profile_images/1307212077887488001/3_ZSk9Zn_400x400.jpg" 
         alt="Zubayer Hossen" 
         style="width: 100px; height: 100px; border-radius: 50%; border: 4px solid #007bff; box-shadow: 0px 5px 10px rgba(0, 0, 0, 0.2);">
  </div>

  <!-- Name & Title -->
  <h3 style="margin: 10px 0 5px; color: #0056b3; font-size: 22px; text-shadow: 1px 1px 3px rgba(0, 0, 0, 0.2);">Zubayer Hossen</h3>
  <p style="margin: 0; font-size: 15px; color: #555; font-style: italic;">WEB DEVELOPER | Digital Transformation Enthusiast</p>

  <!-- Contact Info -->
  <div style="margin-top: 12px; font-size: 15px; color: #333;">
    📞 <a href="tel:+8801580856397" style="color: #007bff; text-decoration: none; font-weight: bold;">+8801580856397</a> &nbsp; | &nbsp;
    ✉ <a href="mailto:fzhossen143r@gmail.com" style="color: #007bff; text-decoration: none; font-weight: bold;">fzhossen143r@gmail.com</a>
  </div>

</div>



      <!-- Footer -->
      <div style="background: #f8f9fa; color: #333; text-align: center; padding: 15px; border-bottom-left-radius: 10px; border-bottom-right-radius: 10px; font-size: 14px;">
        <p style="margin: 5px 0; font-size: 16px;"><strong>📍 Special Economics Care Coaching Centre</strong></p>
        <p style="margin: 5px 0;">📞 Contact: <strong>01906-354505 (Shahadat Hossain)</strong> | <strong>01925-551630 (Abdullah Al Mamun)</strong></p>
        <p style="margin: 5px 0; font-size: 16px; font-weight: bold;">✨ "Unveil the Wonders, Embrace the Adventure – Your Dream Journey Begins Here!" ✨</p>
      </div>

    </div>
  `,
    };

    transporter.sendMail(adminMailOptions, (error, info) => {
      if (error) {
        console.log('Error sending admin email:', error);
      } else {
        console.log('Admin email sent:', info.response);
      }
    });

    // Send Email to User
    const userMailOptions = {
      from: process.env.EMAIL,
      to: email,
      subject: '🎟 Your Tour Registration is Confirmed!',
      html:`<div style="max-width: 650px; margin: auto; font-family: Arial, sans-serif; background: #f4f4f4; padding: 20px; border-radius: 12px; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);">

  <!-- Header Section with Gradient -->
  <div style="background: linear-gradient(135deg, #ff7eb3, #ff758c); color: white; text-align: center; padding: 25px; border-radius: 12px 12px 0 0;">
    <h1 style="margin: 0; font-size: 24px;">🎊 Congratulations, ${name}! 🎊</h1>
    <p style="margin: 5px 0; font-size: 16px;">You're officially part of our Special Tour!</p>
  </div>

  <!-- Welcome Message -->
  <div style="padding: 25px; text-align: center;">
    <h2 style="color: #ff758c; font-size: 22px; margin-bottom: 10px;">🚀 Welcome Aboard!</h2>
    <p style="font-size: 16px; color: #444;">You’re about to embark on an incredible journey with us. Get ready to explore, learn, and create unforgettable memories! Your registration details are below:</p>
  </div>

  <!-- Registration Details -->
  <div style="background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);">
    <table style="width: 100%; border-collapse: collapse;">
      <tr><td style="padding: 10px;"><strong>👤 Name:</strong></td><td>${name}</td></tr>
      <tr><td style="padding: 10px;"><strong>📧 Email:</strong></td><td>${email}</td></tr>
      <tr><td style="padding: 10px;"><strong>📞 Phone:</strong></td><td>${phone}</td></tr>
      <tr><td style="padding: 10px;"><strong>👕 T-Shirt Size:</strong></td><td>${tshirtSize}</td></tr>
      <tr><td style="padding: 10px;"><strong>💰 Fee Status:</strong></td><td style="color: ${feeStatus === 'Paid' ? 'green' : 'red'};"><strong>${feeStatus}</strong></td></tr>
    </table>
  </div>

  <!-- Ticket Download Button -->
  <div style="text-align: center; margin-top: 20px;">
    <a href="https://tour-user.onrender.com/pdfs/registration-${newUser._id}.pdf"
       style="background: linear-gradient(135deg, #ff758c, #ff7eb3); color: white; padding: 14px 24px; text-decoration: none; font-size: 16px; font-weight: bold; border-radius: 8px; box-shadow: 0 2px 6px rgba(0, 0, 0, 0.2);">
      📥 Download Your Registration Ticket
    </a>
  </div>

  <!-- Gallery Section -->
  <div style="margin-top: 30px; background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);">
    <h2 style="text-align: center; color: #ff758c;">📸 Tour Highlights</h2>
    <p style="text-align: center; font-size: 14px; color: #555;">Get a glimpse of the exciting journey ahead!</p>
    <div style="display: flex; flex-wrap: wrap; justify-content: center; gap: 10px;">
          <img src="https://skhobor.com/image/news/Jessore%20Airport%2029032022-1.jpg" style="width: 30%; border-radius: 10px;">
          <img src="https://i.ibb.co/5x5SmwQK/67744235-495910207826030-6821001493089353728-n.jpg" style="width: 30%; border-radius: 10px;">
          <img src="https://www.mawbiz.com.bd/application/views/module/logo_image/logo52.jpg" style="width: 30%; border-radius: 10px;">
        </div>
  </div>

  <!-- Signature Section -->
  <div style="margin-top: 30px; text-align: center; background: linear-gradient(135deg, #ff7eb3, #ff758c); padding: 15px; border-radius: 8px;">
    <p style="color: white; font-size: 16px; margin-bottom: 5px;"><strong>See you soon,</strong></p>
    <img src="https://pbs.twimg.com/profile_images/1307212077887488001/3_ZSk9Zn_400x400.jpg" alt="Signature" style="width: 120px;">
    <p style="color: white; font-size: 14px;">Zubayer Hossen</p>
  </div>

  <!-- Footer -->
  <div style="background: #f8f9fa; text-align: center; padding: 15px; border-radius: 0 0 12px 12px; margin-top: 20px;">
    <p><strong>📍 Special Economic Care Coaching Centre</strong></p>
    <p>📞 Contact: <strong>01906-354505</strong> | <strong>01925-551630</strong></p>
  </div>

</div>
`,
    };

    transporter.sendMail(userMailOptions, (error, info) => {
      if (error) {
        console.log('Error sending user email:', error);
      } else {
        console.log('User email sent:', info.response);
      }
    });

    res.json({ success: true, message: 'Registration successful!', pdfFile: `registration-${newUser._id}.pdf` });

  } catch (error) {
    console.error('Error in registration:', error);
    res.status(500).json({ success: false, message: 'Registration failed!' });
  }
});

module.exports = router;
